[build]
builder = "dockerfile"

[deploy]
startCommand = "docker-compose -f docker-compose.production.yml up"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[services.backend]
name = "rtims-backend"
dockerfilePath = "backend/Dockerfile"
watchPatterns = ["backend/**"]

[services.frontend]
name = "rtims-frontend"
dockerfilePath = "frontend/Dockerfile"
watchPatterns = ["frontend/**"]

[services.database]
name = "rtims-database"
dockerfilePath = "database/Dockerfile.migrator"
watchPatterns = ["database/**"]

[services.redis]
name = "rtims-redis"
image = "redis:7-alpine"